name: Update GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
    permissions:
      contents: write  # Required to push changes to the repository
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install robotframework
          pip install robotframework-pythonlibcore

      - name: Run libdoc.py to generate HTML
        run: python libdoc.py

      - name: Commit and push changes in docs/ only
        env:
          TOKEN: ${{ secrets.GH_PAT }}
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          # Only stage changes in docs/
          git add docs/index.html

          # Commit only if there are changes
          git diff --cached --quiet || git commit -m "Update GitHub Pages"

          # Push only if a commit was made
          if git log -1 --pretty=%B | grep -q "Update GitHub Pages"; then
            git remote set-url origin https://noubar:${TOKEN}@github.com/noubar/RobotFramework-MailClientLibrary.git
            git push origin main
          else
            echo "No changes in docs/ to commit."
          fi